const HttpCodes = {
    Ok: 200,
    Created: 201,
    BadRequest: 400,
    Unauthorized: 401,
    Forbidden: 403,
    NotFound: 404,
    NotPermitted: 405,
    Conflict: 409,
    UnprocessableEntity: 422,
    InternalServerError: 500
}

const Messages = {
    AcknowledgedSuccess: 'Acknowledged successfully',
    AuthTokenNotFound: 'Authentication token not found',
    AuthTokenExpired:'Authentication token expired',
    BadRequest: 'Bad request. missing field(s) in request',
    CoachingLimitExceeded:'Coaching limit exceeded',
    ContentTypeNotFound: 'Content type not found',
    CouponNotFound: 'Coupon not found',
    CouponExpired: 'The coupon has expired',
    CouponUsed: 'The coupon has already been used.',
    CouponValid: 'Coupon is valid',
    CouponNotValid: 'Coupon not valid',
    DataExist:'Data already exists',
    DataCreatedSuccess: 'Data created successfully',
    DataSavedSuccess: 'Data saved successfully to database',
    DataSaveFailed: 'Failed to save data',
    DataRetrievedSuccess: 'Data retrieved successfully',
    DataUpdateSuccess: 'Data updated successfully',
    DataUpdateFail:'Data update failed',
    DataDeletedSuccess: 'Data deleted successfully',
    DeleteFail:'Failed to delete data',
    ErrorOccured: 'An error occurred',
    EmailSentSuccess: 'Email sent successfully',
    ErorrFetchingData: 'An error occured while fetching data',
    InvalidTokenFormat: 'Invalid token format',
    InvalidPassword: 'Invalid password',
    InvalidSchoolCode:'School code is not valid',
    InvalidCoachingCode:'Coaching code is not valid',
    InternalServerError: 'Internal server error',
    IncorrectPassword: 'Wrong password. Try again or click Forgot password to reset it',
    LoginSuccess: 'Successfully logged in',
    LoginUnsuccess:'Login unsuccessful',
    NoPDFUploaded: 'No pdf file uploaded',
    NoTokenBalance:'No token balance',
    NoReferralCode: 'No referral code found',
    NoDataFound: 'Data not found',
    NoOrderDetails: 'Order details not found',
    NoRecordFound: 'No record found',
    OrganizationNotFound: 'Organization profile not found',
    ProcessingStarted: 'Processing started',
    PasswordNotMatched: 'Both passwords didn\'t match',
    PasswordChangedSuccess: 'Password changed successfully',
    RegistrationSuccess: 'Registration successful',
    ReferralCodeIncorrect:'Referral code is not valid',
    SignedOutSuccess: 'Signed out successfully',
    SmsSentSuccess: 'SMS sent successfully to your mobile number',
    UserNotFound: 'User not found',
    UploadFailedDueToLessBalance: 'Book upload failed due to insufficient token balance',
    UserAlreadyExists: 'User already exists',
    UserCodeFound: 'User code found',
    UserCodeNotFound: 'User code not found',
    UserCodeWrong: 'Wrong user code',
    UnprocessableEntity: 'Data has expired / blocked',
    Unauthorized: 'Invalid authentication token',
    ValidOtp:'OTP is valid',
    WrongOtp:'Wrong OTP',
    WrongEmail:'Wrong email id',
}

module.exports = {
    HttpCodes, Messages
}